### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  commentId: T:ChartTools.IO.Configuration.UnsupportedModifierPolicy
  id: UnsupportedModifierPolicy
  parent: ChartTools.IO.Configuration
  children:
  - ChartTools.IO.Configuration.UnsupportedModifierPolicy.Convert
  - ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreChord
  - ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreModifier
  - ChartTools.IO.Configuration.UnsupportedModifierPolicy.ThrowException
  langs:
  - csharp
  - vb
  name: UnsupportedModifierPolicy
  nameWithType: UnsupportedModifierPolicy
  fullName: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  type: Enum
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: UnsupportedModifierPolicy
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 158
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Defines chord modifiers not supported by the target format are handled.
  example: []
  syntax:
    content: 'public enum UnsupportedModifierPolicy : byte'
    content.vb: Public Enum UnsupportedModifierPolicy As Byte
  extensionMethods:
  - ChartTools.IO.Configuration.UnsupportedModifierPolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnsupportedModifierPolicy[])
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy.ThrowException
  commentId: F:ChartTools.IO.Configuration.UnsupportedModifierPolicy.ThrowException
  id: ThrowException
  parent: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  langs:
  - csharp
  - vb
  name: ThrowException
  nameWithType: UnsupportedModifierPolicy.ThrowException
  fullName: ChartTools.IO.Configuration.UnsupportedModifierPolicy.ThrowException
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: ThrowException
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 163
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Throw an exception with the modifier index.
  example: []
  syntax:
    content: ThrowException = 0
    return:
      type: ChartTools.IO.Configuration.UnsupportedModifierPolicy
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy.Convert
  commentId: F:ChartTools.IO.Configuration.UnsupportedModifierPolicy.Convert
  id: Convert
  parent: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  langs:
  - csharp
  - vb
  name: Convert
  nameWithType: UnsupportedModifierPolicy.Convert
  fullName: ChartTools.IO.Configuration.UnsupportedModifierPolicy.Convert
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Convert
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 168
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Convert the modifier to one supported by the format.
  remarks: Will throw an exception if the modifier cannot be converted.
  example: []
  syntax:
    content: Convert = 1
    return:
      type: ChartTools.IO.Configuration.UnsupportedModifierPolicy
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreModifier
  commentId: F:ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreModifier
  id: IgnoreModifier
  parent: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  langs:
  - csharp
  - vb
  name: IgnoreModifier
  nameWithType: UnsupportedModifierPolicy.IgnoreModifier
  fullName: ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreModifier
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: IgnoreModifier
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 172
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Ignore the modifier.
  example: []
  syntax:
    content: IgnoreModifier = 2
    return:
      type: ChartTools.IO.Configuration.UnsupportedModifierPolicy
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreChord
  commentId: F:ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreChord
  id: IgnoreChord
  parent: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  langs:
  - csharp
  - vb
  name: IgnoreChord
  nameWithType: UnsupportedModifierPolicy.IgnoreChord
  fullName: ChartTools.IO.Configuration.UnsupportedModifierPolicy.IgnoreChord
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: IgnoreChord
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 176
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Ignore the chord containing the modifier.
  example: []
  syntax:
    content: IgnoreChord = 3
    return:
      type: ChartTools.IO.Configuration.UnsupportedModifierPolicy
references:
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnsupportedModifierPolicy[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<UnsupportedModifierPolicy>(UnsupportedModifierPolicy, bool, bool, params UnsupportedModifierPolicy[])
  nameWithType: PropertyMerger.Merge<UnsupportedModifierPolicy>(UnsupportedModifierPolicy, bool, bool, params UnsupportedModifierPolicy[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.UnsupportedModifierPolicy>(ChartTools.IO.Configuration.UnsupportedModifierPolicy, bool, bool, params ChartTools.IO.Configuration.UnsupportedModifierPolicy[])
  nameWithType.vb: PropertyMerger.Merge(Of UnsupportedModifierPolicy)(UnsupportedModifierPolicy, Boolean, Boolean, ParamArray UnsupportedModifierPolicy())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.UnsupportedModifierPolicy)(ChartTools.IO.Configuration.UnsupportedModifierPolicy, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.UnsupportedModifierPolicy())
  name.vb: Merge(Of UnsupportedModifierPolicy)(UnsupportedModifierPolicy, Boolean, Boolean, ParamArray UnsupportedModifierPolicy())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.UnsupportedModifierPolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnsupportedModifierPolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
    name: UnsupportedModifierPolicy
    href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
    name: UnsupportedModifierPolicy
    href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
    name: UnsupportedModifierPolicy
    href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.UnsupportedModifierPolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnsupportedModifierPolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
    name: UnsupportedModifierPolicy
    href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
    name: UnsupportedModifierPolicy
    href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
    name: UnsupportedModifierPolicy
    href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  commentId: T:ChartTools.IO.Configuration.UnsupportedModifierPolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  name: UnsupportedModifierPolicy
  nameWithType: UnsupportedModifierPolicy
  fullName: ChartTools.IO.Configuration.UnsupportedModifierPolicy
