### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Chart.Configuration
  commentId: N:ChartTools.IO.Chart.Configuration
  id: ChartTools.IO.Chart.Configuration
  children:
  - ChartTools.IO.Chart.Configuration.ChartReadingConfiguration
  - ChartTools.IO.Chart.Configuration.ChartWritingConfiguration
  - ChartTools.IO.Chart.Configuration.CommonChartConfiguration
  langs:
  - csharp
  - vb
  name: ChartTools.IO.Chart.Configuration
  nameWithType: ChartTools.IO.Chart.Configuration
  fullName: ChartTools.IO.Chart.Configuration
  type: Namespace
  assemblies:
  - ChartTools
references:
- uid: ChartTools.IO.Chart.Configuration.ChartReadingConfiguration
  commentId: T:ChartTools.IO.Chart.Configuration.ChartReadingConfiguration
  parent: ChartTools.IO.Chart.Configuration
  href: ChartTools.IO.Chart.Configuration.ChartReadingConfiguration.html
  name: ChartReadingConfiguration
  nameWithType: ChartReadingConfiguration
  fullName: ChartTools.IO.Chart.Configuration.ChartReadingConfiguration
- uid: ChartTools.IO.Chart.Configuration.ChartWritingConfiguration
  commentId: T:ChartTools.IO.Chart.Configuration.ChartWritingConfiguration
  parent: ChartTools.IO.Chart.Configuration
  href: ChartTools.IO.Chart.Configuration.ChartWritingConfiguration.html
  name: ChartWritingConfiguration
  nameWithType: ChartWritingConfiguration
  fullName: ChartTools.IO.Chart.Configuration.ChartWritingConfiguration
- uid: ChartTools.IO.Chart.Configuration.CommonChartConfiguration
  commentId: T:ChartTools.IO.Chart.Configuration.CommonChartConfiguration
  parent: ChartTools.IO.Chart.Configuration
  href: ChartTools.IO.Chart.Configuration.CommonChartConfiguration.html
  name: CommonChartConfiguration
  nameWithType: CommonChartConfiguration
  fullName: ChartTools.IO.Chart.Configuration.CommonChartConfiguration
- uid: ChartTools.IO.Chart.Configuration
  commentId: N:ChartTools.IO.Chart.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Chart.Configuration
  nameWithType: ChartTools.IO.Chart.Configuration
  fullName: ChartTools.IO.Chart.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Chart
    name: Chart
    href: ChartTools.IO.Chart.html
  - name: .
  - uid: ChartTools.IO.Chart.Configuration
    name: Configuration
    href: ChartTools.IO.Chart.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Chart
    name: Chart
    href: ChartTools.IO.Chart.html
  - name: .
  - uid: ChartTools.IO.Chart.Configuration
    name: Configuration
    href: ChartTools.IO.Chart.Configuration.html
