### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
  commentId: T:ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
  id: ICommonWritingConfiguration
  parent: ChartTools.IO.Configuration.Common
  children:
  - ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy
  langs:
  - csharp
  - vb
  name: ICommonWritingConfiguration
  nameWithType: ICommonWritingConfiguration
  fullName: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
  type: Interface
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonWritingConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: ICommonWritingConfiguration
    path: ../ChartTools/IO/Configuration/Common/ICommonWritingConfiguration.cs
    startLine: 2
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  syntax:
    content: 'public interface ICommonWritingConfiguration : ICommonConfiguration'
    content.vb: Public Interface ICommonWritingConfiguration Inherits ICommonConfiguration
  inheritedMembers:
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  extensionMethods:
  - ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonWritingConfiguration[])
- uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy
  id: UnsupportedModifierPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
  langs:
  - csharp
  - vb
  name: UnsupportedModifierPolicy
  nameWithType: ICommonWritingConfiguration.UnsupportedModifierPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy
  type: Property
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonWritingConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: UnsupportedModifierPolicy
    path: ../ChartTools/IO/Configuration/Common/ICommonWritingConfiguration.cs
    startLine: 5
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  example: []
  syntax:
    content: UnsupportedModifierPolicy UnsupportedModifierPolicy { get; init; }
    parameters: []
    return:
      type: ChartTools.IO.Configuration.UnsupportedModifierPolicy
    content.vb: Property UnsupportedModifierPolicy As UnsupportedModifierPolicy
  overload: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy*
references:
- uid: ChartTools.IO.Configuration.Common
  commentId: N:ChartTools.IO.Configuration.Common
  href: ChartTools.html
  name: ChartTools.IO.Configuration.Common
  nameWithType: ChartTools.IO.Configuration.Common
  fullName: ChartTools.IO.Configuration.Common
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  - name: .
  - uid: ChartTools.IO.Configuration.Common
    name: Common
    href: ChartTools.IO.Configuration.Common.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  - name: .
  - uid: ChartTools.IO.Configuration.Common
    name: Common
    href: ChartTools.IO.Configuration.Common.html
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_DuplicateTrackObjectPolicy
  name: DuplicateTrackObjectPolicy
  nameWithType: ICommonConfiguration.DuplicateTrackObjectPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_OverlappingStarPowerPolicy
  name: OverlappingStarPowerPolicy
  nameWithType: ICommonConfiguration.OverlappingStarPowerPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_SnappedNotesPolicy
  name: SnappedNotesPolicy
  nameWithType: ICommonConfiguration.SnappedNotesPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
- uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonWritingConfiguration[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<ICommonWritingConfiguration>(ICommonWritingConfiguration, bool, bool, params ICommonWritingConfiguration[])
  nameWithType: PropertyMerger.Merge<ICommonWritingConfiguration>(ICommonWritingConfiguration, bool, bool, params ICommonWritingConfiguration[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.Common.ICommonWritingConfiguration>(ChartTools.IO.Configuration.Common.ICommonWritingConfiguration, bool, bool, params ChartTools.IO.Configuration.Common.ICommonWritingConfiguration[])
  nameWithType.vb: PropertyMerger.Merge(Of ICommonWritingConfiguration)(ICommonWritingConfiguration, Boolean, Boolean, ParamArray ICommonWritingConfiguration())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.Common.ICommonWritingConfiguration)(ChartTools.IO.Configuration.Common.ICommonWritingConfiguration, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.Common.ICommonWritingConfiguration())
  name.vb: Merge(Of ICommonWritingConfiguration)(ICommonWritingConfiguration, Boolean, Boolean, ParamArray ICommonWritingConfiguration())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.Common.ICommonWritingConfiguration,System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonWritingConfiguration[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
    name: ICommonWritingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
    name: ICommonWritingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
    name: ICommonWritingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.Common.ICommonWritingConfiguration,System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonWritingConfiguration[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
    name: ICommonWritingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
    name: ICommonWritingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration
    name: ICommonWritingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
  commentId: T:ChartTools.IO.Configuration.Common.ICommonConfiguration
  parent: ChartTools.IO.Configuration.Common
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  name: ICommonConfiguration
  nameWithType: ICommonConfiguration
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.IO.Configuration.UnsupportedModifierPolicy
  commentId: T:ChartTools.IO.Configuration.UnsupportedModifierPolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.UnsupportedModifierPolicy.html
  name: UnsupportedModifierPolicy
  nameWithType: UnsupportedModifierPolicy
  fullName: ChartTools.IO.Configuration.UnsupportedModifierPolicy
- uid: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy*
  commentId: Overload:ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy
  href: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.html#ChartTools_IO_Configuration_Common_ICommonWritingConfiguration_UnsupportedModifierPolicy
  name: UnsupportedModifierPolicy
  nameWithType: ICommonWritingConfiguration.UnsupportedModifierPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonWritingConfiguration.UnsupportedModifierPolicy
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
