### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
  commentId: T:ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
  id: ICommonReadingConfiguration
  parent: ChartTools.IO.Configuration.Common
  children:
  - ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy
  langs:
  - csharp
  - vb
  name: ICommonReadingConfiguration
  nameWithType: ICommonReadingConfiguration
  fullName: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
  type: Interface
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonReadingConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: ICommonReadingConfiguration
    path: ../ChartTools/IO/Configuration/Common/ICommonReadingConfiguration.cs
    startLine: 2
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  syntax:
    content: 'public interface ICommonReadingConfiguration : ICommonConfiguration'
    content.vb: Public Interface ICommonReadingConfiguration Inherits ICommonConfiguration
  inheritedMembers:
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  extensionMethods:
  - ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonReadingConfiguration[])
- uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy
  id: UnknownSectionPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
  langs:
  - csharp
  - vb
  name: UnknownSectionPolicy
  nameWithType: ICommonReadingConfiguration.UnknownSectionPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy
  type: Property
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonReadingConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: UnknownSectionPolicy
    path: ../ChartTools/IO/Configuration/Common/ICommonReadingConfiguration.cs
    startLine: 4
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  syntax:
    content: UnknownSectionPolicy UnknownSectionPolicy { get; }
    parameters: []
    return:
      type: ChartTools.IO.Configuration.UnknownSectionPolicy
    content.vb: ReadOnly Property UnknownSectionPolicy As UnknownSectionPolicy
  overload: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy*
references:
- uid: ChartTools.IO.Configuration.Common
  commentId: N:ChartTools.IO.Configuration.Common
  href: ChartTools.html
  name: ChartTools.IO.Configuration.Common
  nameWithType: ChartTools.IO.Configuration.Common
  fullName: ChartTools.IO.Configuration.Common
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  - name: .
  - uid: ChartTools.IO.Configuration.Common
    name: Common
    href: ChartTools.IO.Configuration.Common.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  - name: .
  - uid: ChartTools.IO.Configuration.Common
    name: Common
    href: ChartTools.IO.Configuration.Common.html
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_DuplicateTrackObjectPolicy
  name: DuplicateTrackObjectPolicy
  nameWithType: ICommonConfiguration.DuplicateTrackObjectPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_OverlappingStarPowerPolicy
  name: OverlappingStarPowerPolicy
  nameWithType: ICommonConfiguration.OverlappingStarPowerPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_SnappedNotesPolicy
  name: SnappedNotesPolicy
  nameWithType: ICommonConfiguration.SnappedNotesPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
- uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonReadingConfiguration[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<ICommonReadingConfiguration>(ICommonReadingConfiguration, bool, bool, params ICommonReadingConfiguration[])
  nameWithType: PropertyMerger.Merge<ICommonReadingConfiguration>(ICommonReadingConfiguration, bool, bool, params ICommonReadingConfiguration[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.Common.ICommonReadingConfiguration>(ChartTools.IO.Configuration.Common.ICommonReadingConfiguration, bool, bool, params ChartTools.IO.Configuration.Common.ICommonReadingConfiguration[])
  nameWithType.vb: PropertyMerger.Merge(Of ICommonReadingConfiguration)(ICommonReadingConfiguration, Boolean, Boolean, ParamArray ICommonReadingConfiguration())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.Common.ICommonReadingConfiguration)(ChartTools.IO.Configuration.Common.ICommonReadingConfiguration, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.Common.ICommonReadingConfiguration())
  name.vb: Merge(Of ICommonReadingConfiguration)(ICommonReadingConfiguration, Boolean, Boolean, ParamArray ICommonReadingConfiguration())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.Common.ICommonReadingConfiguration,System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonReadingConfiguration[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
    name: ICommonReadingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
    name: ICommonReadingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
    name: ICommonReadingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.Common.ICommonReadingConfiguration,System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonReadingConfiguration[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
    name: ICommonReadingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
    name: ICommonReadingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration
    name: ICommonReadingConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
  commentId: T:ChartTools.IO.Configuration.Common.ICommonConfiguration
  parent: ChartTools.IO.Configuration.Common
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  name: ICommonConfiguration
  nameWithType: ICommonConfiguration
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy*
  commentId: Overload:ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy
  href: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.html#ChartTools_IO_Configuration_Common_ICommonReadingConfiguration_UnknownSectionPolicy
  name: UnknownSectionPolicy
  nameWithType: ICommonReadingConfiguration.UnknownSectionPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonReadingConfiguration.UnknownSectionPolicy
- uid: ChartTools.IO.Configuration.UnknownSectionPolicy
  commentId: T:ChartTools.IO.Configuration.UnknownSectionPolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  name: UnknownSectionPolicy
  nameWithType: UnknownSectionPolicy
  fullName: ChartTools.IO.Configuration.UnknownSectionPolicy
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
