### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.LyricEventSource
  commentId: T:ChartTools.IO.Configuration.LyricEventSource
  id: LyricEventSource
  parent: ChartTools.IO.Configuration
  children:
  - ChartTools.IO.Configuration.LyricEventSource.GlobalEvents
  - ChartTools.IO.Configuration.LyricEventSource.Vocals
  langs:
  - csharp
  - vb
  name: LyricEventSource
  nameWithType: LyricEventSource
  fullName: ChartTools.IO.Configuration.LyricEventSource
  type: Enum
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: LyricEventSource
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 27
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Define where lyrics are obtained when writing a format that defines lyrics as events.
  example: []
  syntax:
    content: 'public enum LyricEventSource : byte'
    content.vb: Public Enum LyricEventSource As Byte
  extensionMethods:
  - ChartTools.IO.Configuration.LyricEventSource.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.LyricEventSource[])
- uid: ChartTools.IO.Configuration.LyricEventSource.GlobalEvents
  commentId: F:ChartTools.IO.Configuration.LyricEventSource.GlobalEvents
  id: GlobalEvents
  parent: ChartTools.IO.Configuration.LyricEventSource
  langs:
  - csharp
  - vb
  name: GlobalEvents
  nameWithType: LyricEventSource.GlobalEvents
  fullName: ChartTools.IO.Configuration.LyricEventSource.GlobalEvents
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: GlobalEvents
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 32
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Obtain lyrics from <xref href="ChartTools.Song.GlobalEvents" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: GlobalEvents = 0
    return:
      type: ChartTools.IO.Configuration.LyricEventSource
- uid: ChartTools.IO.Configuration.LyricEventSource.Vocals
  commentId: F:ChartTools.IO.Configuration.LyricEventSource.Vocals
  id: Vocals
  parent: ChartTools.IO.Configuration.LyricEventSource
  langs:
  - csharp
  - vb
  name: Vocals
  nameWithType: LyricEventSource.Vocals
  fullName: ChartTools.IO.Configuration.LyricEventSource.Vocals
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Vocals
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 36
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Obtain lyrics from the <xref href="ChartTools.InstrumentSet.Vocals" data-throw-if-not-resolved="false"></xref> instrument.
  example: []
  syntax:
    content: Vocals = 1
    return:
      type: ChartTools.IO.Configuration.LyricEventSource
references:
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
- uid: ChartTools.IO.Configuration.LyricEventSource.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.LyricEventSource[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<LyricEventSource>(LyricEventSource, bool, bool, params LyricEventSource[])
  nameWithType: PropertyMerger.Merge<LyricEventSource>(LyricEventSource, bool, bool, params LyricEventSource[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.LyricEventSource>(ChartTools.IO.Configuration.LyricEventSource, bool, bool, params ChartTools.IO.Configuration.LyricEventSource[])
  nameWithType.vb: PropertyMerger.Merge(Of LyricEventSource)(LyricEventSource, Boolean, Boolean, ParamArray LyricEventSource())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.LyricEventSource)(ChartTools.IO.Configuration.LyricEventSource, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.LyricEventSource())
  name.vb: Merge(Of LyricEventSource)(LyricEventSource, Boolean, Boolean, ParamArray LyricEventSource())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.LyricEventSource,System.Boolean,System.Boolean,ChartTools.IO.Configuration.LyricEventSource[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.LyricEventSource
    name: LyricEventSource
    href: ChartTools.IO.Configuration.LyricEventSource.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.LyricEventSource
    name: LyricEventSource
    href: ChartTools.IO.Configuration.LyricEventSource.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.LyricEventSource
    name: LyricEventSource
    href: ChartTools.IO.Configuration.LyricEventSource.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.LyricEventSource,System.Boolean,System.Boolean,ChartTools.IO.Configuration.LyricEventSource[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.LyricEventSource
    name: LyricEventSource
    href: ChartTools.IO.Configuration.LyricEventSource.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.LyricEventSource
    name: LyricEventSource
    href: ChartTools.IO.Configuration.LyricEventSource.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.LyricEventSource
    name: LyricEventSource
    href: ChartTools.IO.Configuration.LyricEventSource.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.Song.GlobalEvents
  commentId: P:ChartTools.Song.GlobalEvents
  href: ChartTools.Song.html#ChartTools_Song_GlobalEvents
  name: GlobalEvents
  nameWithType: Song.GlobalEvents
  fullName: ChartTools.Song.GlobalEvents
- uid: ChartTools.IO.Configuration.LyricEventSource
  commentId: T:ChartTools.IO.Configuration.LyricEventSource
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.LyricEventSource.html
  name: LyricEventSource
  nameWithType: LyricEventSource
  fullName: ChartTools.IO.Configuration.LyricEventSource
- uid: ChartTools.InstrumentSet.Vocals
  commentId: P:ChartTools.InstrumentSet.Vocals
  href: ChartTools.InstrumentSet.html#ChartTools_InstrumentSet_Vocals
  name: Vocals
  nameWithType: InstrumentSet.Vocals
  fullName: ChartTools.InstrumentSet.Vocals
