### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.UnknownSectionPolicy
  commentId: T:ChartTools.IO.Configuration.UnknownSectionPolicy
  id: UnknownSectionPolicy
  parent: ChartTools.IO.Configuration
  children:
  - ChartTools.IO.Configuration.UnknownSectionPolicy.Store
  - ChartTools.IO.Configuration.UnknownSectionPolicy.ThrowException
  langs:
  - csharp
  - vb
  name: UnknownSectionPolicy
  nameWithType: UnknownSectionPolicy
  fullName: ChartTools.IO.Configuration.UnknownSectionPolicy
  type: Enum
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: UnknownSectionPolicy
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 143
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Defines how unknown sections or Midi chunks are handled.
  example: []
  syntax:
    content: 'public enum UnknownSectionPolicy : byte'
    content.vb: Public Enum UnknownSectionPolicy As Byte
  extensionMethods:
  - ChartTools.IO.Configuration.UnknownSectionPolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnknownSectionPolicy[])
- uid: ChartTools.IO.Configuration.UnknownSectionPolicy.ThrowException
  commentId: F:ChartTools.IO.Configuration.UnknownSectionPolicy.ThrowException
  id: ThrowException
  parent: ChartTools.IO.Configuration.UnknownSectionPolicy
  langs:
  - csharp
  - vb
  name: ThrowException
  nameWithType: UnknownSectionPolicy.ThrowException
  fullName: ChartTools.IO.Configuration.UnknownSectionPolicy.ThrowException
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: ThrowException
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 148
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Throw an exception with the section or chunk header.
  example: []
  syntax:
    content: ThrowException = 0
    return:
      type: ChartTools.IO.Configuration.UnknownSectionPolicy
- uid: ChartTools.IO.Configuration.UnknownSectionPolicy.Store
  commentId: F:ChartTools.IO.Configuration.UnknownSectionPolicy.Store
  id: Store
  parent: ChartTools.IO.Configuration.UnknownSectionPolicy
  langs:
  - csharp
  - vb
  name: Store
  nameWithType: UnknownSectionPolicy.Store
  fullName: ChartTools.IO.Configuration.UnknownSectionPolicy.Store
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Store
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 152
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Store the raw data to be included when writing.
  example: []
  syntax:
    content: Store = 1
    return:
      type: ChartTools.IO.Configuration.UnknownSectionPolicy
references:
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
- uid: ChartTools.IO.Configuration.UnknownSectionPolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnknownSectionPolicy[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<UnknownSectionPolicy>(UnknownSectionPolicy, bool, bool, params UnknownSectionPolicy[])
  nameWithType: PropertyMerger.Merge<UnknownSectionPolicy>(UnknownSectionPolicy, bool, bool, params UnknownSectionPolicy[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.UnknownSectionPolicy>(ChartTools.IO.Configuration.UnknownSectionPolicy, bool, bool, params ChartTools.IO.Configuration.UnknownSectionPolicy[])
  nameWithType.vb: PropertyMerger.Merge(Of UnknownSectionPolicy)(UnknownSectionPolicy, Boolean, Boolean, ParamArray UnknownSectionPolicy())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.UnknownSectionPolicy)(ChartTools.IO.Configuration.UnknownSectionPolicy, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.UnknownSectionPolicy())
  name.vb: Merge(Of UnknownSectionPolicy)(UnknownSectionPolicy, Boolean, Boolean, ParamArray UnknownSectionPolicy())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.UnknownSectionPolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnknownSectionPolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.UnknownSectionPolicy
    name: UnknownSectionPolicy
    href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.UnknownSectionPolicy
    name: UnknownSectionPolicy
    href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.UnknownSectionPolicy
    name: UnknownSectionPolicy
    href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.UnknownSectionPolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.UnknownSectionPolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.UnknownSectionPolicy
    name: UnknownSectionPolicy
    href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.UnknownSectionPolicy
    name: UnknownSectionPolicy
    href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.UnknownSectionPolicy
    name: UnknownSectionPolicy
    href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.IO.Configuration.UnknownSectionPolicy
  commentId: T:ChartTools.IO.Configuration.UnknownSectionPolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.UnknownSectionPolicy.html
  name: UnknownSectionPolicy
  nameWithType: UnknownSectionPolicy
  fullName: ChartTools.IO.Configuration.UnknownSectionPolicy
