### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  commentId: T:ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  id: OverlappingSpecialPhrasePolicy
  parent: ChartTools.IO.Configuration
  children:
  - ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Cut
  - ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Ignore
  - ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.ThrowException
  langs:
  - csharp
  - vb
  name: OverlappingSpecialPhrasePolicy
  nameWithType: OverlappingSpecialPhrasePolicy
  fullName: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  type: Enum
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: OverlappingSpecialPhrasePolicy
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 42
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Defines how overlapping star power phrases should be handled.
  example: []
  syntax:
    content: 'public enum OverlappingSpecialPhrasePolicy : byte'
    content.vb: Public Enum OverlappingSpecialPhrasePolicy As Byte
  extensionMethods:
  - ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy[])
- uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.ThrowException
  commentId: F:ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.ThrowException
  id: ThrowException
  parent: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  langs:
  - csharp
  - vb
  name: ThrowException
  nameWithType: OverlappingSpecialPhrasePolicy.ThrowException
  fullName: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.ThrowException
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: ThrowException
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 47
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Throw an exception.
  example: []
  syntax:
    content: ThrowException = 0
    return:
      type: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
- uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Ignore
  commentId: F:ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Ignore
  id: Ignore
  parent: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  langs:
  - csharp
  - vb
  name: Ignore
  nameWithType: OverlappingSpecialPhrasePolicy.Ignore
  fullName: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Ignore
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Ignore
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 51
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Ignore the overlapping phrase.
  example: []
  syntax:
    content: Ignore = 1
    return:
      type: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
- uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Cut
  commentId: F:ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Cut
  id: Cut
  parent: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  langs:
  - csharp
  - vb
  name: Cut
  nameWithType: OverlappingSpecialPhrasePolicy.Cut
  fullName: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.Cut
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Cut
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 55
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Cut the length of the first phrase to the start of the next one.
  example: []
  syntax:
    content: Cut = 2
    return:
      type: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
references:
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
- uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<OverlappingSpecialPhrasePolicy>(OverlappingSpecialPhrasePolicy, bool, bool, params OverlappingSpecialPhrasePolicy[])
  nameWithType: PropertyMerger.Merge<OverlappingSpecialPhrasePolicy>(OverlappingSpecialPhrasePolicy, bool, bool, params OverlappingSpecialPhrasePolicy[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy>(ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy, bool, bool, params ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy[])
  nameWithType.vb: PropertyMerger.Merge(Of OverlappingSpecialPhrasePolicy)(OverlappingSpecialPhrasePolicy, Boolean, Boolean, ParamArray OverlappingSpecialPhrasePolicy())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy)(ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy())
  name.vb: Merge(Of OverlappingSpecialPhrasePolicy)(OverlappingSpecialPhrasePolicy, Boolean, Boolean, ParamArray OverlappingSpecialPhrasePolicy())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
    name: OverlappingSpecialPhrasePolicy
    href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
    name: OverlappingSpecialPhrasePolicy
    href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
    name: OverlappingSpecialPhrasePolicy
    href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
    name: OverlappingSpecialPhrasePolicy
    href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
    name: OverlappingSpecialPhrasePolicy
    href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
    name: OverlappingSpecialPhrasePolicy
    href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  commentId: T:ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  name: OverlappingSpecialPhrasePolicy
  nameWithType: OverlappingSpecialPhrasePolicy
  fullName: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
