### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.TrackObjectSource
  commentId: T:ChartTools.IO.Configuration.TrackObjectSource
  id: TrackObjectSource
  parent: ChartTools.IO.Configuration
  children:
  - ChartTools.IO.Configuration.TrackObjectSource.Easy
  - ChartTools.IO.Configuration.TrackObjectSource.Expert
  - ChartTools.IO.Configuration.TrackObjectSource.Hard
  - ChartTools.IO.Configuration.TrackObjectSource.Medium
  - ChartTools.IO.Configuration.TrackObjectSource.Merge
  langs:
  - csharp
  - vb
  name: TrackObjectSource
  nameWithType: TrackObjectSource
  fullName: ChartTools.IO.Configuration.TrackObjectSource
  type: Enum
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: TrackObjectSource
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 116
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Difficulty of the <xref href="ChartTools.Track" data-throw-if-not-resolved="false"></xref> to serve as a source of for track objects for which the target format requires these objects to be the same across all difficulties.
  remarks: Can be cast from <xref href="ChartTools.Difficulty" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: 'public enum TrackObjectSource : byte'
    content.vb: Public Enum TrackObjectSource As Byte
  extensionMethods:
  - ChartTools.IO.Configuration.TrackObjectSource.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.TrackObjectSource[])
- uid: ChartTools.IO.Configuration.TrackObjectSource.Easy
  commentId: F:ChartTools.IO.Configuration.TrackObjectSource.Easy
  id: Easy
  parent: ChartTools.IO.Configuration.TrackObjectSource
  langs:
  - csharp
  - vb
  name: Easy
  nameWithType: TrackObjectSource.Easy
  fullName: ChartTools.IO.Configuration.TrackObjectSource.Easy
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Easy
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 121
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Use the objects from the <xref href="ChartTools.Difficulty.Easy" data-throw-if-not-resolved="false"></xref> track.
  example: []
  syntax:
    content: Easy = 0
    return:
      type: ChartTools.IO.Configuration.TrackObjectSource
- uid: ChartTools.IO.Configuration.TrackObjectSource.Medium
  commentId: F:ChartTools.IO.Configuration.TrackObjectSource.Medium
  id: Medium
  parent: ChartTools.IO.Configuration.TrackObjectSource
  langs:
  - csharp
  - vb
  name: Medium
  nameWithType: TrackObjectSource.Medium
  fullName: ChartTools.IO.Configuration.TrackObjectSource.Medium
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Medium
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 125
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Use the objects from the <xref href="ChartTools.Difficulty.Medium" data-throw-if-not-resolved="false"></xref> track.
  example: []
  syntax:
    content: Medium = 1
    return:
      type: ChartTools.IO.Configuration.TrackObjectSource
- uid: ChartTools.IO.Configuration.TrackObjectSource.Hard
  commentId: F:ChartTools.IO.Configuration.TrackObjectSource.Hard
  id: Hard
  parent: ChartTools.IO.Configuration.TrackObjectSource
  langs:
  - csharp
  - vb
  name: Hard
  nameWithType: TrackObjectSource.Hard
  fullName: ChartTools.IO.Configuration.TrackObjectSource.Hard
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Hard
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 129
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Use the objects from the <xref href="ChartTools.Difficulty.Hard" data-throw-if-not-resolved="false"></xref> track.
  example: []
  syntax:
    content: Hard = 2
    return:
      type: ChartTools.IO.Configuration.TrackObjectSource
- uid: ChartTools.IO.Configuration.TrackObjectSource.Expert
  commentId: F:ChartTools.IO.Configuration.TrackObjectSource.Expert
  id: Expert
  parent: ChartTools.IO.Configuration.TrackObjectSource
  langs:
  - csharp
  - vb
  name: Expert
  nameWithType: TrackObjectSource.Expert
  fullName: ChartTools.IO.Configuration.TrackObjectSource.Expert
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Expert
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 133
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Use the objects from the <xref href="ChartTools.Difficulty.Expert" data-throw-if-not-resolved="false"></xref> track.
  example: []
  syntax:
    content: Expert = 3
    return:
      type: ChartTools.IO.Configuration.TrackObjectSource
- uid: ChartTools.IO.Configuration.TrackObjectSource.Merge
  commentId: F:ChartTools.IO.Configuration.TrackObjectSource.Merge
  id: Merge
  parent: ChartTools.IO.Configuration.TrackObjectSource
  langs:
  - csharp
  - vb
  name: Merge
  nameWithType: TrackObjectSource.Merge
  fullName: ChartTools.IO.Configuration.TrackObjectSource.Merge
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: Merge
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 137
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Combine the unique track objects from all the tracks in the instrument.
  example: []
  syntax:
    content: Merge = 4
    return:
      type: ChartTools.IO.Configuration.TrackObjectSource
references:
- uid: ChartTools.Track
  commentId: T:ChartTools.Track
  parent: ChartTools
  href: ChartTools.Track.html
  name: Track
  nameWithType: Track
  fullName: ChartTools.Track
- uid: ChartTools.Difficulty
  commentId: T:ChartTools.Difficulty
  parent: ChartTools
  href: ChartTools.Difficulty.html
  name: Difficulty
  nameWithType: Difficulty
  fullName: ChartTools.Difficulty
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
- uid: ChartTools.IO.Configuration.TrackObjectSource.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.TrackObjectSource[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<TrackObjectSource>(TrackObjectSource, bool, bool, params TrackObjectSource[])
  nameWithType: PropertyMerger.Merge<TrackObjectSource>(TrackObjectSource, bool, bool, params TrackObjectSource[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.TrackObjectSource>(ChartTools.IO.Configuration.TrackObjectSource, bool, bool, params ChartTools.IO.Configuration.TrackObjectSource[])
  nameWithType.vb: PropertyMerger.Merge(Of TrackObjectSource)(TrackObjectSource, Boolean, Boolean, ParamArray TrackObjectSource())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.TrackObjectSource)(ChartTools.IO.Configuration.TrackObjectSource, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.TrackObjectSource())
  name.vb: Merge(Of TrackObjectSource)(TrackObjectSource, Boolean, Boolean, ParamArray TrackObjectSource())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.TrackObjectSource,System.Boolean,System.Boolean,ChartTools.IO.Configuration.TrackObjectSource[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.TrackObjectSource
    name: TrackObjectSource
    href: ChartTools.IO.Configuration.TrackObjectSource.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.TrackObjectSource
    name: TrackObjectSource
    href: ChartTools.IO.Configuration.TrackObjectSource.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.TrackObjectSource
    name: TrackObjectSource
    href: ChartTools.IO.Configuration.TrackObjectSource.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.TrackObjectSource,System.Boolean,System.Boolean,ChartTools.IO.Configuration.TrackObjectSource[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.TrackObjectSource
    name: TrackObjectSource
    href: ChartTools.IO.Configuration.TrackObjectSource.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.TrackObjectSource
    name: TrackObjectSource
    href: ChartTools.IO.Configuration.TrackObjectSource.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.TrackObjectSource
    name: TrackObjectSource
    href: ChartTools.IO.Configuration.TrackObjectSource.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools
  commentId: N:ChartTools
  href: ChartTools.html
  name: ChartTools
  nameWithType: ChartTools
  fullName: ChartTools
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.Difficulty.Easy
  commentId: F:ChartTools.Difficulty.Easy
  href: ChartTools.Difficulty.html#ChartTools_Difficulty_Easy
  name: Easy
  nameWithType: Difficulty.Easy
  fullName: ChartTools.Difficulty.Easy
- uid: ChartTools.IO.Configuration.TrackObjectSource
  commentId: T:ChartTools.IO.Configuration.TrackObjectSource
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.TrackObjectSource.html
  name: TrackObjectSource
  nameWithType: TrackObjectSource
  fullName: ChartTools.IO.Configuration.TrackObjectSource
- uid: ChartTools.Difficulty.Medium
  commentId: F:ChartTools.Difficulty.Medium
  href: ChartTools.Difficulty.html#ChartTools_Difficulty_Medium
  name: Medium
  nameWithType: Difficulty.Medium
  fullName: ChartTools.Difficulty.Medium
- uid: ChartTools.Difficulty.Hard
  commentId: F:ChartTools.Difficulty.Hard
  href: ChartTools.Difficulty.html#ChartTools_Difficulty_Hard
  name: Hard
  nameWithType: Difficulty.Hard
  fullName: ChartTools.Difficulty.Hard
- uid: ChartTools.Difficulty.Expert
  commentId: F:ChartTools.Difficulty.Expert
  href: ChartTools.Difficulty.html#ChartTools_Difficulty_Expert
  name: Expert
  nameWithType: Difficulty.Expert
  fullName: ChartTools.Difficulty.Expert
