### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  commentId: T:ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  id: DuplicateTrackObjectPolicy
  parent: ChartTools.IO.Configuration
  children:
  - ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeAll
  - ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeFirst
  - ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.ThrowException
  langs:
  - csharp
  - vb
  name: DuplicateTrackObjectPolicy
  nameWithType: DuplicateTrackObjectPolicy
  fullName: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  type: Enum
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: DuplicateTrackObjectPolicy
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 8
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Defines how duplicate track objects are handled.
  example: []
  syntax:
    content: 'public enum DuplicateTrackObjectPolicy : byte'
    content.vb: Public Enum DuplicateTrackObjectPolicy As Byte
  extensionMethods:
  - ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.DuplicateTrackObjectPolicy[])
- uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.ThrowException
  commentId: F:ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.ThrowException
  id: ThrowException
  parent: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  langs:
  - csharp
  - vb
  name: ThrowException
  nameWithType: DuplicateTrackObjectPolicy.ThrowException
  fullName: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.ThrowException
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: ThrowException
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 13
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Throw an exception with the position.
  example: []
  syntax:
    content: ThrowException = 0
    return:
      type: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
- uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeFirst
  commentId: F:ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeFirst
  id: IncludeFirst
  parent: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  langs:
  - csharp
  - vb
  name: IncludeFirst
  nameWithType: DuplicateTrackObjectPolicy.IncludeFirst
  fullName: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeFirst
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: IncludeFirst
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 17
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Include only the first object
  example: []
  syntax:
    content: IncludeFirst = 1
    return:
      type: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
- uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeAll
  commentId: F:ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeAll
  id: IncludeAll
  parent: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  langs:
  - csharp
  - vb
  name: IncludeAll
  nameWithType: DuplicateTrackObjectPolicy.IncludeAll
  fullName: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.IncludeAll
  type: Field
  source:
    remote:
      path: ChartTools/IO/Configuration/Enums.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: IncludeAll
    path: ../ChartTools/IO/Configuration/Enums.cs
    startLine: 21
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration
  summary: Include all objects.
  example: []
  syntax:
    content: IncludeAll = 2
    return:
      type: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
references:
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
- uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.DuplicateTrackObjectPolicy[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<DuplicateTrackObjectPolicy>(DuplicateTrackObjectPolicy, bool, bool, params DuplicateTrackObjectPolicy[])
  nameWithType: PropertyMerger.Merge<DuplicateTrackObjectPolicy>(DuplicateTrackObjectPolicy, bool, bool, params DuplicateTrackObjectPolicy[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.DuplicateTrackObjectPolicy>(ChartTools.IO.Configuration.DuplicateTrackObjectPolicy, bool, bool, params ChartTools.IO.Configuration.DuplicateTrackObjectPolicy[])
  nameWithType.vb: PropertyMerger.Merge(Of DuplicateTrackObjectPolicy)(DuplicateTrackObjectPolicy, Boolean, Boolean, ParamArray DuplicateTrackObjectPolicy())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.DuplicateTrackObjectPolicy)(ChartTools.IO.Configuration.DuplicateTrackObjectPolicy, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.DuplicateTrackObjectPolicy())
  name.vb: Merge(Of DuplicateTrackObjectPolicy)(DuplicateTrackObjectPolicy, Boolean, Boolean, ParamArray DuplicateTrackObjectPolicy())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.DuplicateTrackObjectPolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.DuplicateTrackObjectPolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
    name: DuplicateTrackObjectPolicy
    href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
    name: DuplicateTrackObjectPolicy
    href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
    name: DuplicateTrackObjectPolicy
    href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.DuplicateTrackObjectPolicy,System.Boolean,System.Boolean,ChartTools.IO.Configuration.DuplicateTrackObjectPolicy[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
    name: DuplicateTrackObjectPolicy
    href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
    name: DuplicateTrackObjectPolicy
    href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
    name: DuplicateTrackObjectPolicy
    href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  commentId: T:ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  name: DuplicateTrackObjectPolicy
  nameWithType: DuplicateTrackObjectPolicy
  fullName: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
