### YamlMime:ManagedReference
items:
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
  commentId: T:ChartTools.IO.Configuration.Common.ICommonConfiguration
  id: ICommonConfiguration
  parent: ChartTools.IO.Configuration.Common
  children:
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  langs:
  - csharp
  - vb
  name: ICommonConfiguration
  nameWithType: ICommonConfiguration
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration
  type: Interface
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: ICommonConfiguration
    path: ../ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
    startLine: 6
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  summary: Configuration object to direct the reading or writing of a file
  remarks: If <a href="https://learn.microsoft.com/dotnet/csharp/language-reference/keywords/null">null</a>, the default configuration for the file format will be used.
  example: []
  syntax:
    content: public interface ICommonConfiguration
    content.vb: Public Interface ICommonConfiguration
  extensionMethods:
  - ChartTools.IO.Configuration.Common.ICommonConfiguration.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonConfiguration[])
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  id: DuplicateTrackObjectPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  langs:
  - csharp
  - vb
  name: DuplicateTrackObjectPolicy
  nameWithType: ICommonConfiguration.DuplicateTrackObjectPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  type: Property
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: DuplicateTrackObjectPolicy
    path: ../ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
    startLine: 9
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  summary: Defines how duplicate track objects are handled.
  example: []
  syntax:
    content: DuplicateTrackObjectPolicy DuplicateTrackObjectPolicy { get; }
    parameters: []
    return:
      type: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
    content.vb: ReadOnly Property DuplicateTrackObjectPolicy As DuplicateTrackObjectPolicy
  overload: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy*
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  id: OverlappingStarPowerPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  langs:
  - csharp
  - vb
  name: OverlappingStarPowerPolicy
  nameWithType: ICommonConfiguration.OverlappingStarPowerPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  type: Property
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: OverlappingStarPowerPolicy
    path: ../ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
    startLine: 12
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  summary: Defines how overlapping star power phrases should be handled.
  example: []
  syntax:
    content: OverlappingSpecialPhrasePolicy OverlappingStarPowerPolicy { get; }
    parameters: []
    return:
      type: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
    content.vb: ReadOnly Property OverlappingStarPowerPolicy As OverlappingSpecialPhrasePolicy
  overload: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy*
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  commentId: P:ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  id: SnappedNotesPolicy
  parent: ChartTools.IO.Configuration.Common.ICommonConfiguration
  langs:
  - csharp
  - vb
  name: SnappedNotesPolicy
  nameWithType: ICommonConfiguration.SnappedNotesPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  type: Property
  source:
    remote:
      path: ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
      branch: 64-rework-docs-website
      repo: https://github.com/TheBoxyBear/charttools.git
    id: SnappedNotesPolicy
    path: ../ChartTools/IO/Configuration/Common/ICommonConfiguration.cs
    startLine: 15
  assemblies:
  - ChartTools
  namespace: ChartTools.IO.Configuration.Common
  summary: Defines how notes within ticks of each other are handled during a Midi operation.
  example: []
  syntax:
    content: SnappedNotesPolicy SnappedNotesPolicy { get; }
    parameters: []
    return:
      type: ChartTools.IO.Configuration.SnappedNotesPolicy
    content.vb: ReadOnly Property SnappedNotesPolicy As SnappedNotesPolicy
  overload: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy*
references:
- uid: ChartTools.IO.Configuration.Common
  commentId: N:ChartTools.IO.Configuration.Common
  href: ChartTools.html
  name: ChartTools.IO.Configuration.Common
  nameWithType: ChartTools.IO.Configuration.Common
  fullName: ChartTools.IO.Configuration.Common
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  - name: .
  - uid: ChartTools.IO.Configuration.Common
    name: Common
    href: ChartTools.IO.Configuration.Common.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  - name: .
  - uid: ChartTools.IO.Configuration.Common
    name: Common
    href: ChartTools.IO.Configuration.Common.html
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.ChartTools.Tools.PropertyMerger.Merge``1(System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonConfiguration[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  parent: ChartTools.Tools.PropertyMerger
  definition: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<ICommonConfiguration>(ICommonConfiguration, bool, bool, params ICommonConfiguration[])
  nameWithType: PropertyMerger.Merge<ICommonConfiguration>(ICommonConfiguration, bool, bool, params ICommonConfiguration[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<ChartTools.IO.Configuration.Common.ICommonConfiguration>(ChartTools.IO.Configuration.Common.ICommonConfiguration, bool, bool, params ChartTools.IO.Configuration.Common.ICommonConfiguration[])
  nameWithType.vb: PropertyMerger.Merge(Of ICommonConfiguration)(ICommonConfiguration, Boolean, Boolean, ParamArray ICommonConfiguration())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of ChartTools.IO.Configuration.Common.ICommonConfiguration)(ChartTools.IO.Configuration.Common.ICommonConfiguration, Boolean, Boolean, ParamArray ChartTools.IO.Configuration.Common.ICommonConfiguration())
  name.vb: Merge(Of ICommonConfiguration)(ICommonConfiguration, Boolean, Boolean, ParamArray ICommonConfiguration())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.Common.ICommonConfiguration,System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonConfiguration[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
    name: ICommonConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  - name: '>'
  - name: (
  - uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
    name: ICommonConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
    name: ICommonConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(ChartTools.IO.Configuration.Common.ICommonConfiguration,System.Boolean,System.Boolean,ChartTools.IO.Configuration.Common.ICommonConfiguration[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
    name: ICommonConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  - name: )
  - name: (
  - uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
    name: ICommonConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - uid: ChartTools.IO.Configuration.Common.ICommonConfiguration
    name: ICommonConfiguration
    href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  commentId: M:ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
  isExternal: true
  href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  name: Merge<T>(T, bool, bool, params T[])
  nameWithType: PropertyMerger.Merge<T>(T, bool, bool, params T[])
  fullName: ChartTools.Tools.PropertyMerger.Merge<T>(T, bool, bool, params T[])
  nameWithType.vb: PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  fullName.vb: ChartTools.Tools.PropertyMerger.Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  name.vb: Merge(Of T)(T, Boolean, Boolean, ParamArray T())
  spec.csharp:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: params
  - name: " "
  - name: T
  - name: '['
  - name: ']'
  - name: )
  spec.vb:
  - uid: ChartTools.Tools.PropertyMerger.Merge``1(``0,System.Boolean,System.Boolean,``0[])
    name: Merge
    href: ChartTools.Tools.PropertyMerger.html#ChartTools_Tools_PropertyMerger_Merge__1___0_System_Boolean_System_Boolean___0___
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: ','
  - name: " "
  - name: ParamArray
  - name: " "
  - name: T
  - name: (
  - name: )
  - name: )
- uid: ChartTools.Tools.PropertyMerger
  commentId: T:ChartTools.Tools.PropertyMerger
  parent: ChartTools.Tools
  href: ChartTools.Tools.PropertyMerger.html
  name: PropertyMerger
  nameWithType: PropertyMerger
  fullName: ChartTools.Tools.PropertyMerger
- uid: ChartTools.Tools
  commentId: N:ChartTools.Tools
  href: ChartTools.html
  name: ChartTools.Tools
  nameWithType: ChartTools.Tools
  fullName: ChartTools.Tools
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.Tools
    name: Tools
    href: ChartTools.Tools.html
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy*
  commentId: Overload:ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_DuplicateTrackObjectPolicy
  name: DuplicateTrackObjectPolicy
  nameWithType: ICommonConfiguration.DuplicateTrackObjectPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.DuplicateTrackObjectPolicy
- uid: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  commentId: T:ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy.html
  name: DuplicateTrackObjectPolicy
  nameWithType: DuplicateTrackObjectPolicy
  fullName: ChartTools.IO.Configuration.DuplicateTrackObjectPolicy
- uid: ChartTools.IO.Configuration
  commentId: N:ChartTools.IO.Configuration
  href: ChartTools.html
  name: ChartTools.IO.Configuration
  nameWithType: ChartTools.IO.Configuration
  fullName: ChartTools.IO.Configuration
  spec.csharp:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
  spec.vb:
  - uid: ChartTools
    name: ChartTools
    href: ChartTools.html
  - name: .
  - uid: ChartTools.IO
    name: IO
    href: ChartTools.IO.html
  - name: .
  - uid: ChartTools.IO.Configuration
    name: Configuration
    href: ChartTools.IO.Configuration.html
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy*
  commentId: Overload:ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_OverlappingStarPowerPolicy
  name: OverlappingStarPowerPolicy
  nameWithType: ICommonConfiguration.OverlappingStarPowerPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.OverlappingStarPowerPolicy
- uid: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  commentId: T:ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy.html
  name: OverlappingSpecialPhrasePolicy
  nameWithType: OverlappingSpecialPhrasePolicy
  fullName: ChartTools.IO.Configuration.OverlappingSpecialPhrasePolicy
- uid: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy*
  commentId: Overload:ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
  href: ChartTools.IO.Configuration.Common.ICommonConfiguration.html#ChartTools_IO_Configuration_Common_ICommonConfiguration_SnappedNotesPolicy
  name: SnappedNotesPolicy
  nameWithType: ICommonConfiguration.SnappedNotesPolicy
  fullName: ChartTools.IO.Configuration.Common.ICommonConfiguration.SnappedNotesPolicy
- uid: ChartTools.IO.Configuration.SnappedNotesPolicy
  commentId: T:ChartTools.IO.Configuration.SnappedNotesPolicy
  parent: ChartTools.IO.Configuration
  href: ChartTools.IO.Configuration.SnappedNotesPolicy.html
  name: SnappedNotesPolicy
  nameWithType: SnappedNotesPolicy
  fullName: ChartTools.IO.Configuration.SnappedNotesPolicy
